// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo3q4MF74cANKx2T6iLi3TqMAXnEbp7D8',
    appId: '1:849145401529:web:75e7d6d978241c91cd4b68',
    messagingSenderId: '849145401529',
    projectId: 'app-de-psicologia-suayed',
    authDomain: 'app-de-psicologia-suayed.firebaseapp.com',
    storageBucket: 'app-de-psicologia-suayed.firebasestorage.app',
    measurementId: 'G-1JH7VG81R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYF6YFWkQCPEgZb1AN6N7PNqci9oG_nws',
    appId: '1:849145401529:android:6e7800c33df3abc7cd4b68',
    messagingSenderId: '849145401529',
    projectId: 'app-de-psicologia-suayed',
    storageBucket: 'app-de-psicologia-suayed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAagHjcDiccA1x-3s7QdHy7QYSZsUKga_o',
    appId: '1:849145401529:ios:463c82eec8f51b9bcd4b68',
    messagingSenderId: '849145401529',
    projectId: 'app-de-psicologia-suayed',
    storageBucket: 'app-de-psicologia-suayed.firebasestorage.app',
    iosBundleId: 'com.example.suayed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAagHjcDiccA1x-3s7QdHy7QYSZsUKga_o',
    appId: '1:849145401529:ios:463c82eec8f51b9bcd4b68',
    messagingSenderId: '849145401529',
    projectId: 'app-de-psicologia-suayed',
    storageBucket: 'app-de-psicologia-suayed.firebasestorage.app',
    iosBundleId: 'com.example.suayed',
  );

}